[tool.ruff]
select = ["ALL"]
line-length = 100
target-version = "py311"
show-fixes = true
ignore = [
  "TD001",
  "TD002",
  "TD003",
  "FIX001",
  "FIX002",
  "PGH004",
  "D102",
] # Should be enabled for multi developers context

[tool.ruff.isort]
known-first-party = ["your_project"]
